services:
  - type: web
    name: instagram-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: VERIFY_TOKEN
        sync: false
      - key: PAGE_ACCESS_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
